### ISSUE TITLE
1.0.0부터 아이템액자에서 아이템이 빠집니다 화이트월드 보호 해도요

### ISSUE THREAD

**Issue by shdudwns** [HmHmmHm/SimpleArea#10]
구동기 문제인가요?

**Comment by ghost** [comment]
@shdudwns 
아이템 액자에 아이템이 들어가긴 하나요?

**Comment by shdudwns** [comment]
아이템은 들어가집니다
유저빌때는 안되고요

2017. 6. 11. 오후 9:51에 "ZINGDING" <notifications@github.com>님이 작성:
