### ISSUE TITLE
현재 PocketMine 버전에서 심플에리어가 구제 불능 상태입니다.

### ISSUE THREAD

**Issue by nnnlog** [HmHmmHm/SimpleArea#11]
/섬 또는 /땅 명령어는 잘 쳐지는데 뒤에 옵션을 넣으면 커맨드가 없다고 뜹니다.

**Comment by HmHmmHm** [comment]
개발을 마무리 한 이후로 시간이 상당히
오래 되었기 때문에 api가 분명 달라졌을거에요
프로토콜을 갱신해서 쓰셔야 합니다 ;-;

**Comment by HmHmmHm** [comment]
Closed #12
