### ISSUE TITLE
EconomyS의 GPL 라이센스에 따라 SimpleArea도 GPLv3 라이센스이어야 합니다.

### ISSUE THREAD

**Issue by nnnlog** [HmHmmHm/SimpleArea#13]
EconomyS의 GPL 라이센스에 따라 SimpleArea도 데이즈율라가 아닌 GPLv3 라이센스이어야 합니다.

**Comment by alvin0319** [comment]
맞는 말입니다

**Comment by HmHmmHm** [comment]
GPL 라이센스는 단순히 유저가 임의로 설치한
라이브러리를 기반으로 API 함수를 사용하는 것 일때는,

즉 직접적으로 타인의 코드를 내장하지 않은 프로젝트 일땐,

그 사용을 강제하거나 라이센스를
전염시킬 수 있는 저작권적 근거가 없습니다.

API 인터페이스 코드 자체도 아니고

API call 함수의 사용을 저작권 주장하는 것은
무리가 있다는 DCMA 판결도 등장했습니다.

JAVA의 API call interface 관련 저작권분쟁 판례
( http://www.zdnet.co.kr/news/news_view.asp?artice_id=20160530084945&type=det&re= )

**Comment by nnnlog** [comment]
@HmHmmHm 호오.. 그렇군요. http://cafe.naver.com/minecraftpe/2684270
이 글은 어떻게 되는건가요?

**Comment by nnnlog** [comment]
@HmHmmHm 그리고 EconomyAPI::getInstance()-> 이렇게 API를 사용하는 경우도 GPL 전염이 되지 않는건가요?

**Comment by HmHmmHm** [comment]
@nnnlog 

개발자는 자신이 만든 공유 라이브러리를 배포하고도
타 개발자들이 자신의 인터페이스 무단사용을 원치 않는다면

모두가 접근 가능한 공용 인터페이스로 함수를 등록하는 것이 아니라,
직접적인 프로토콜의 사용을 원치 않는다는 것을  명시한 후

해당 함수를 자신만의 어플리케이션 메모리에 가둬놓거나
별도로 직접 클래스나 소스를  내장해야만 해당 메모리 함수에
접근할 수 있도록 코드를 통해 접근을 제한해야 맞다고 봅니다.
자바에선 조금 어렵겠지만 불가능한 것도 아니에요,

JAVA 판례에서 보듯 단순히 패키지명이나 인터페이스명을
인용 사용했다는 것만으로 저작권을 주장하기엔
그와 관련된 법적근거가 명확치 않습니다.

**Comment by nnnlog** [comment]
@HmHmmHm 그래서 결론이 EconomyAPI::getInstance()-> 이렇게 API를 사용하는 경우도 GPL 전염이 되지 않는건가요..?

**Comment by HmHmmHm** [comment]
@nnnlog 네, 오라클 보다 돈 많으면 가능할지도?

**Comment by nnnlog** [comment]
@HmHmmHm 오라클이 아니라 원본님 아닌가여.. (원본님의 이코노미 물어봤는데 갑자기 오라클ㅇ..)

**Comment by HmHmmHm** [comment]
@nnnlog 
JAVA의 API call interface 관련 저작권분쟁 판례
( http://www.zdnet.co.kr/news/news_view.asp?artice_id=20160530084945&type=det&re= )

`오라클이 비슷한 주장을 했으나 거액을 들이고도 실패함`

**Comment by PresentKim** [comment]
@HmHmmHm 오라클은 API링킹 문제가 아니라 API구조가 같다-에 대한 문제일걸요?

**Comment by HmHmmHm** [comment]
@PresentKim 사실 C에서처럼 .lib 모듈링킹 시
코드파일 복붙되는 것 같은 링킹도 아니고

단순히 함수사용 만으로..? 저작권?
을 주장하기엔 상당한 무리가 있죠 실제로..

**Comment by HmHmmHm** [comment]
(알림)

플러그인 저작권 필요한거 있나요?

제가 만든 거라면 무료로 풀테니
아래 게시글로 요청하세요-

http://cafe.naver.com/minecraftpe/2685934
