### ISSUE TITLE
임대공간 생성 관련 이슈

### ISSUE THREAD

**Issue by nnnlog** [HmHmmHm/SimpleArea#5]
@maru @ZINGDING @onebone

만약에 A 라는 유저가 a 라는 섬을 만들어 임대공간을 생성하면 영역 공유가 되어있지 않는 사람들도 그 섬을 부술 수 있게됩니다.

**Comment by ghost** [comment]
@ParkChanSol 섬을 만든다니요?

**Comment by nnnlog** [comment]
@ZINGDING 섬을 사서 임대공간 생성 시에 영역공유가 되지 않은 플레이어도 그 섬을 부술 수 있습니다

**Comment by ghost** [comment]
정확히 얘기해주세요.
섬을 부술수 있는거에요 아니면 임대공간만 부술수 있는거에요
아니면 섬하고 임대공간을 둘 다 부술수 있는거에요.
@ParkChanSol

**Comment by Mintos74** [comment]
임대공간만 부술 수 있습니다.

**Comment by nnnlog** [comment]
@ZINGDING 임대공간만 부술 수 있답니다(By @Mintos74 )

**Comment by ghost** [comment]
@Mintos74 
해당 오류는 꽤 예전에 고쳐진걸로 아는데
검토해보고 연락드리겠습니다.

**Comment by nnnlog** [comment]
@ZINGDING 감사합니다
